### ISSUE TITLE
[Assignment 2 Task 3] Incomplete path for `bzImage` and `vmlinux`

### ISSUE THREAD

**Issue by hywhuangyuwei** [nus-cs5250/24s#14]
In Task 3: Debugging with GDB, the assignment guide says:

> Launch QEMU with the command below to start your Linux kernel. This command sets up QEMU to wait for a debugger connection. KASLR is disabled to simplify debugging.
> ```
> qemu-system-x86_64 -s -S -nographic -kernel bzImage -append 'console=ttyS0 nokaslr'
> ```
> Next, open GDB to connect to the running QEMU instance by using the command:
> ```
> gdb vmlinux
> ```

Here cannot decide which `bzImage` and `vmlinux` should be used.

Have tried `/boot/vmlinuz-6.7.0` and `linux-6.7/arch/x86/boot/compressed/vmlinux`, both resulting in GDB says `No debugging symbols found in xxx`.

When intending to run `watch jiffies_64`, GDB will say `No symbol table is loaded.  Use the "file" command`.

**Comment by shnjmn** [comment]
`vmlinux` should be the `linux-6.7/vmlinux`. 

GDB needs the debug symbols from this ELF file, and it cannot find the symbols from a compressed image.
