### ISSUE TITLE
No response when launching QEMU using the given command

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs5250/24s#15]
I'm using a Windows 11 host. When I follow the QEMU command given in task 3 of assignment 2, QEMU does not produce any output in 15 minutes:
![Screenshot 2024-03-04 220902](https://github.com/nus-cs5250/24s/assets/67496158/9831c303-d9f8-4732-9dec-ca42665e50b4)

At this time, I can go to QEMU's monitor if I hit ctrl+A followed by C, but it does not recognize "gdb". I have GDB installed on the VM.
![Screenshot 2024-03-04 221011](https://github.com/nus-cs5250/24s/assets/67496158/6c5cff50-9eeb-473b-9644-f735b34d097d)

I can get QEMU running if I drop the `-S` in the command. However, I get `Kernel panic - not syncing: VFS: Unable to mount root fs on unkn)` in the end, despite that VirtualBox has no problem booting the compiled kernel.

![Screenshot 2024-03-04 221117](https://github.com/nus-cs5250/24s/assets/67496158/23bfa6be-9d4a-44da-a460-7d7d33e0cdb2)

(side question) I can't show the full history because I don't know how to move up. I've tried (ctrl+↑), (ctrl+shift+↑) and (shift+↑) but none worked.

**Comment by shnjmn** [comment]
You should open a new terminal and execute GDB.

**Comment by zihaowrez** [comment]
Hi Jiamin,

Could you teach me how to open a new terminal? According to [this](https://stackoverflow.com/questions/6710555/how-to-use-qemu-to-run-a-non-gui-os-on-the-terminal) `-nographic` with `console=ttyS0` should open a new terminal for me.

Thanks!

**Comment by shnjmn** [comment]
You should execute GDB in your VM, not in QEMU. The GDB will then (in the next step) connect to QEMU via TCP.

Open your Windows Terminal, use ssh to connect to your VM then you get a new shell to your VM.

**Comment by zihaowrez** [comment]
Hi Jiamin,

Thanks and I'm now able to run GDB. However, my GDB does not pause before I get a kernel panic:
![image](https://github.com/nus-cs5250/24s/assets/67496158/d33b0c99-d4c7-4176-9652-8386d1dd4d8d)

VirtualBox had no problem booting this compiled kernel. Would it be possible for you to see what I might have done wrong here? Thank you!

**Comment by shnjmn** [comment]
If you remember what you did in the previous assignment, you should realise that it's normal that you see a kernel panic (if you failed to set the breakpoint), since no initrd is provided.

It's abnormal to see `(No debugging symbols found in /mnt/linux/vmlinux)`.
Please ensure you followed the instruction carefully.

![image](https://github.com/nus-cs5250/24s/assets/138759442/b27ed731-aa61-426b-8a55-150daf029474)
