### ISSUE TITLE
Warning about trailing whitespaces

### ISSUE THREAD

**Issue by Rubatozh** [nus-cs5250/24s#17]
![T NUV~7FE9E}@JZNCYF3O37](https://github.com/nus-cs5250/24s/assets/73592273/9d185ed9-d07b-43cb-9c06-b3ace9303d8d)
I would like to make sure if it is a problem that it warns about whitespace errors when applying new syscall patch to linux since it includes the word "error" but it is just a warning ad is "nothing to worry about" according to my search, and the kernel with new syscall compiles and functions well

**Comment by shnjmn** [comment]
It will be fine if applying the patch using `git apply --reject --whitespace=fix` works perfectly on your patch.

But it's still good to fix the problem if possible.
