### ISSUE TITLE
What is the expected comment for Question 4?

### ISSUE THREAD

**Issue by JothamWong** [nus-cs5250/24s#19]
It is initially hello.ko, but we renamed the file to modcpid.c as part of our submission.
So do we change it to modcpid.ko or remains as hello.ko?

**Comment by JothamWong** [comment]
Also since there may not be enough time to resolve this by submission deadline, and because I think it's a minor issue anyways, I guess both hello.ko and modcpid.ko would be accepted

**Comment by shnjmn** [comment]
Yes both of them will be accepted.
