### ISSUE TITLE
Whether final submission of hack-tetris.c requires reading from stdin and performing search?

### ISSUE THREAD

**Issue by Rubatozh** [nus-cs5250/24s#26]
I guess the final submission of hack-tetris.c only has to read from arguments and then update the score at the right location, without reading from stdin and performing the search? Can I get a clarification about this? Thanks!

**Comment by shnjmn** [comment]
You should perform the search dynamically during runtime. Hardcoding the offset in your code is not allowed. During grading, another victim process will be used, and the offset can vary.

**Comment by Rubatozh** [comment]
So I assume the program still has to read from stdin the value? Further, excluding wrong addresses should be done by program itself rather than man, right? But I don't think it is feasible to perform search and exclude wrong values if the value is not so specified...

**Comment by taraxacum45e9a** [comment]
> So I assume the program still has to read from stdin the value? 

Yes

> Further, excluding wrong addresses should be done by program itself rather than man, right? 

Yes, should be done by program.

> But I don't think it is feasible to perform search and exclude wrong values if the value is not so specified...

Of course, so it's necessary to provide the value repeatedly.

**Comment by Rubatozh** [comment]
Thank you!
