### ISSUE TITLE
For qn2, is onebyte device's initial value required to be specified 0xff?

### ISSUE THREAD

**Issue by Rubatozh** [nus-cs5250/24s#31]
<img width="224" alt="Screen Shot 2024-04-04 at 18 36 57" src="https://github.com/nus-cs5250/24s/assets/73592273/f7e93887-ba28-45fa-8f0e-80de3251ee0c">
Might be a silly question but just would like to be sure...I guess mknod itself cannot set the initial value of device?

**Comment by shnjmn** [comment]
Yes.

It's initialized in "onebyte_init"

**Comment by Rubatozh** [comment]
I see. Thanks!
