### ISSUE TITLE
Is dd or tee's bad address error considered as memory errors for our driver?

### ISSUE THREAD

**Issue by Rubatozh** [nus-cs5250/24s#32]
As Task 3 requires the driver to be free of memory errors, just want to make sure if these app's errors are deemed as our driver's errors.

**Comment by shnjmn** [comment]
What is the error number? If it's EFAULT, normally we don't consider it a memory error.

**Comment by Rubatozh** [comment]
Thx. Also, should we consider the scenario like

echo 12x > tmp.in
$ sudo dd if=tmp.in of=/dev/factorial0 bs=1

where block write begins with valid input and ends with invalid input? Or we can simply neglect this?

**Comment by shnjmn** [comment]
The input will always be either valid or empty.

**Comment by shnjmn** [comment]
BTW, by convention, you should always open a new issue for a new question, with proper title, so that others can refer to it.
